service: api-customer

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /customer
          method: any

plugins:
  - serverless-offline